development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: dev_db
  pool: 5
  host: localhost
  username: rails_user
  password: secret

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: testing_db
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: prod_db
  pool: 5
